name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install

      - run: pnpm run test:run --coverage
        env:
          CI: true

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    needs: [lint, test]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - run: pnpm install

      - run: pnpm run build

      - run: pnpm run check-size

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: latest
          access: public
          dry-run: false
          check-version: true
          greater-version-only: true
