name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npm run test:run
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npm run build

      - run: npm run check-size

      - uses: JS-DevTools/npm-publish@v3
        if: github.ref_name == 'main'
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: latest
          access: public
          dry-run: false
          strategy: upgrade

      - uses: anothrNick/github-tag-action@v1
        if: github.ref_name == 'main' && steps.publish.outputs.type
        env:
          CUSTOM_TAG: ${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v2
        if: github.ref_name == 'main' && steps.publish.outputs.type
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          body: 'Changelog: https://github.com/iendeavor/pinia-plugin-persistedstate-2/blob/${{ steps.publish.outputs.version }}/CHANGELOG.md'

      - run: npm pack

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            *.tgz

  node-lts:
    runs-on: ubuntu-latest

    needs:
      - build

    name: 'Build example - ${{ matrix.example-directory }}'

    strategy:
      matrix:
        example-directory:
          - ionic-capacitor-preferences
          - localforage-example
          - nuxt-2-client-example
          - nuxt-3-universal-example
          - nuxt-bridge-example
          - pinia-orm-example
          - quasar-example
          - vike-example
          - vue-3-example

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: artifact

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: |
          cd examples/${{matrix.example-directory}}
          npm ci
          npm add ../../*.tgz
          npm run build

  node-16:
    runs-on: ubuntu-latest

    needs:
      - build

    name: 'Build example - ${{ matrix.example-directory }}'

    strategy:
      matrix:
        example-directory:
          - vue-2-example

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: artifact

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: |
          cd examples/${{matrix.example-directory}}
          npm ci
          npm add ../../*.tgz
          npm run build
