name: Release

on:
  schedule:
    - cron '0 0 * * 4'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test:run
        env:
          CI: true

      - name: Build
        run: pnpm run build

      - name: Check size
        run: pnpm run check-size

      - name: Release
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          pnpm run release

      - name: Push changes
        uses: ad-m/github-push-action@master
